sudo: required
services: [ docker ]
language: node_js
node_js:
- 6
- 7
- 8
before_install:
- docker --rm -p 9000:9000 --name minio -e MINIO_ACCESS_KEY=admin -e MINIO_SECRET_KEY=test minio/minio server /export



script:
- npm test
